### PR TITLE
feat: previous policies, last policy change timer, file viewer, ipfs bug

### LINKED ISSUE #106: Policy Format
Is there a specific reason why the policy should be a link to a pdf file on IPFS?

Why can't it be a page on the interface? That would be more natural.

FireShot Capture 1060 -  - https___ipfs kleros io_ipfs_QmbqgkZoGu7jJ8nTqee4NypEhK7YVBEJJmPJbJxz8B

### LINKED ISSUE #373: curate: fetching bug 0.5 sec ipfs not found (sometimes)
curate: fetching bug 0.5 sec ipfs not found (sometimes), on an item

### PR DESCRIPTION
**Pull request by kemuru**

### CODE REVIEW

**Comment by tractorss** [comment]
@coderabbitai review

File: src/components/display-selector.tsx [hunk 1]
```diff
@@ -99,9 +114,9 @@ const ImageWithLoading = ({ src, alt, linkImage }: ImageWithLoadingProps) => {
 
   if (linkImage)
     return (
-      <a href={src} target="_blank" rel="noopener noreferrer">
+      <ImageLinkButton type="button" onClick={() => openAttachment(src)}>
```
Comment (tractorss) [inline src/components/display-selector.tsx]: is type="button" necessary here? It is already a button element

File: src/components/evidence-file-link.tsx [hunk 2]
```diff
@@ -0,0 +1,59 @@
+import React from 'react'
+import styled, { css } from 'styled-components'
+import { smallScreenStyle } from 'styles/small-screen-style'
+import { buttonReset } from 'styles/button-reset'
+import { parseIpfs } from 'utils/ipfs-parse'
+import { useAttachment } from 'hooks/use-attachment'
+import PaperclipIcon from 'assets/icons/paperclip.svg?react'
```
Comment (tractorss) [inline src/components/evidence-file-link.tsx]: is "?react" needed here, we already have `svgr` plugin for react, so this shouldn't be necessary

Comment (tractorss) [reply src/components/evidence-file-link.tsx]: Same for other similar imports

File: src/components/evidence-file-link.tsx [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+/**
+ * "View attached file" button rendered in the evidence timeline card
+ * extras slot. Shared between classic/light (`request-timelines.tsx`)
+ * and permanent (`permanent-request-timelines.tsx`).
+ */
+const EvidenceFileLink: React.FC<{ fileURI: string }> = ({ fileURI }) => {
+  const openAttachment = useAttachment()
+  return (
+    <StyledFileLink
+      type="button"
```
Comment (tractorss) [inline src/components/evidence-file-link.tsx]: The only reason for this might be that this is rendered inside a \<form\> tag, but I don't think it is here.

File: src/utils/fetch-policy-history.ts [hunk 4]
```diff
@@ -0,0 +1,341 @@
...
+  txHash: string
+}
+
+export type PolicyFetchMode = 'full' | 'latest'
+
+const META_EVIDENCE_TOPIC = utils.id('MetaEvidence(uint256,string)')
+
+/**
+ * Per-chain public RPC endpoints prepended in front of Alchemy. Public
+ * Gnosis RPCs allow much larger `getLogs` block ranges (100k) than Alchemy's
```
Comment (tractorss) [inline src/utils/fetch-policy-history.ts]: 100k block range on public?

File: src/utils/fetch-policy-history.ts [hunk 5]
```diff
@@ -0,0 +1,341 @@
...
+      try {
+        const [metaEvidenceURI] = utils.defaultAbiCoder.decode(
+          ['string'],
+          log.data,
+        ) as [string]
+        const response = await fetch(parseIpfs(metaEvidenceURI))
+        if (!response.ok) throw new Error(`HTTP ${response.status}`)
+        const json = await response.json()
+        const fileURI =
+          typeof json.fileURI === 'string' && json.fileURI.startsWith('/ipfs/')
```
Comment (tractorss) [inline src/utils/fetch-policy-history.ts]: This is too strict with identifying a fileURI, it could just be an ipfsHash too, or a different ipfs scheme.

File: src/components/evidence-file-link.tsx (hunk 2 above)
Comment (kemuru) [reply src/components/evidence-file-link.tsx]: if i remove the ?react thing it crashes, but its fixed by adding in the vite config this "svgr({ include: '**/*.svg' }),"

File: src/utils/fetch-policy-history.ts (hunk 4 above)
Comment (kemuru) [reply src/utils/fetch-policy-history.ts]: actually the comment was not accurate, changed it

File: src/components/evidence-file-link.tsx (hunk 2 above)
Comment (tractorss) [reply src/components/evidence-file-link.tsx]: hmm, yes that should be the svgr config. I assumed that it would be defaulting to all svgs. 

But yes better than ?react

**Review by tractorss — APPROVED** [review]
